using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pekistirec.Engine.EventLog
{
    public enum EventLogTipleri
    {               
        KULLANICI_KAYIT_BASARILI,
        KULLANICI_KAYIT_HATA,
        KULLANICI_KAYIT_EXTERNAL_FACEBOOK_BASARILI,
        KULLANICI_KAYIT_EXTERNAL_FACEBOOK_HATA,
        KULLANICI_KAYIT_EXTERNAL_GOOGLE_BASARILI,
        KULLANICI_KAYIT_EXTERNAL_GOOGLE_HATA,
        //
        KULLANICI_GIRIS_BASARILI,
        KULLANICI_GIRIS_HATA,
        KULLANICI_GIRIS_EXTERNAL_FACEBOOK_BASARILI,
        KULLANICI_GIRIS_EXTERNAL_GOOGLE_BASARILI,
        KULLANICI_GIRIS_EXTERNAL_FACEBOOK_HATA,
        KULLANICI_GIRIS_EXTERNAL_GOOGLE_HATA,
        //
        KULLANICI_BILGI_DEGISTI_FACEBOOK_USER_ID,
        KULLANICI_BILGI_DEGISTI_GOOGLE_USER_ID,
        KULLANICI_BILGI_DEGISTI_GOOGLE_REFRESH_TOKEN,
        KULLANICI_BILGI_DEGISTI_ADSOYAD,
        KULLANICI_BILGI_DEGISTI_BRANS,
        KULLANICI_BILGI_DEGISTI_OKUL,
        KULLANICI_BILGI_DEGISTI_MUDUR,
        KULLANICI_BILGI_DEGISTI_HAKKIMDA,
        KULLANICI_BILGI_DEGISTI_AVATAR,
        KULLANICI_BILGI_DEGISTI_SIFRE,
        KULLANICI_BILGI_DEGISTI_SIFRE_HATA,
        KULLANICI_BILGI_DEGISTI_SIFRE_TANIMLANDI,
        //
        ARKADASLIK_ISTEGI_GONDERILDI,
        ARKADASLIK_ISTEGI_ONAYLANDI,
        ARKADASLIK_IPTAL_EDILDI,
        //
        ADMIN_AYARLAR_DEGISTI,
        ADMIN_AYARLAR_DEGISTI_HATA,
        //
        DOKUMAN_YUKLENDI,
        DOKUMAN_YUKLENEMEDI_HATA,
        DOKUMAN_YUKLENDI_ANCAK_FTS_EKLENMEDI,
        //
        DOKUMAN_FILTRELE,
        DOKUMAN_ARA_BASLIK,
        DOKUMAN_ARA_ICERIK

    }
}